version: '3'
services:
    db:
        image: 'postgres'
        container_name: 'my_postgres'
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=mydb
        #   Maps first port 5432 (localhost) to second port 5432 on the container.
        ports:
            - '5432:5432'
        # volumes:
        #     - ./postgres-data:/var/lib/postgresql/data
